### ISSUE TITLE
JSON Output handled by Function

### ISSUE THREAD

**Issue by jorymorrison** [jorymorrison/MLD#12]
It would be great if we could create a function to handle output of the software. 

It would be great to define a function that takes all of our values (tone, sentiment, lexical signature, date, title, etc...) and handles formatting for us using json_dumps. We could pretty print to a file.

**Comment by Matthew-Zorumski** [comment]
in process of being completed in #10 will be closed when branch finished

**Comment by jorymorrison** [comment]
#15
