### ISSUE TITLE
Web Crawler

### ISSUE THREAD

**Issue by Matthew-Zorumski** [jorymorrison/MLD#17]
Decide on how corpus will be generated and how web crawler will act.

**Comment by jorymorrison** [comment]
Today we talked about using curl, grep, and awk/sed in the shell to build a simple crawler.

Here's a snippet we came up with.

`curl -i https://www.cnn.com | grep -Eo '*\/[0-9]{4}\/[0-9]{2}\/[0-9]{2}\/[a-z/-]+.html' |  awk '$0="https://www.cnn.com"$0'`

I recommend you build a shell script that uses this logic, in a recursive manner, to go to n depth into each root level link. The final output should be a text file that we can eventually feed into the crawler.

**Comment by jorymorrison** [comment]
Also, remember that you were using a different regular expression than I was. It might be a good idea to post it here.

**Comment by Matthew-Zorumski** [comment]
`(((http|https):\/\/www.cnn.com\/[0-9]{4}\/[0-9]{2}\/[0-9]{2}\/[a-z/-]+.html)|(\/[0-9]{4}\/[0-9]{2}\/[0-9]{2}\/[a-z/-]+.html))`

**Comment by Matthew-Zorumski** [comment]
solved in #21 merged in #22.
