### ISSUE TITLE
Argument Support with ArgParse (or similiar)

### ISSUE THREAD

**Issue by jorymorrison** [jorymorrison/MLD#20]
MLD should support the input of an article as an argument. 

Example usage:

`mld.py https://cnn.com/fadsfdsafadsfdsa`

It would also be convenient for it to take as input a list of urls in text format.

Example usage:

`mld.py -i myfile.txt`

I suggest looking at ArgParse or a similiar library as argument parsing can be difficult and unmaintainable.

Please update the README to reflect any new usages/functionality as part of this work.

**Comment by Matthew-Zorumski** [comment]
solved in #21 will be closed after merge.

**Comment by jorymorrison** [comment]
Now in #22. You got rid of #21 due to the number of issues.
