### ISSUE TITLE
Incorrect slash when saving results (linux)

### ISSUE THREAD

**Issue by Matthew-Zorumski** [jorymorrison/MLD#3]
When saving the results of the program, the program uses a forward slash after attempting to save to the MLD folder resulting in the saving of the file in the home directory as MLD\{tittle}.

**Comment by jorymorrison** [comment]
The desired behavior, in my mind, would be to have the results saved to a "results" directory located inside the directory of execution.

**Comment by jorymorrison** [comment]
Looks like you addressed this in 1d083c7. Will Close pending PR.

**Comment by jorymorrison** [comment]
Let's leave open until the PR goes through to have better trace-ability.

**Comment by jorymorrison** [comment]
Fixed in #8
