### ISSUE TITLE
Tone Analyzer usage is old

### ISSUE THREAD

**Issue by jorymorrison** [jorymorrison/MLD#4]
It appears that in the two years since this was maintained the Watson API has been updated. 

It appears that Watson API only expects a secret key, not a username and password.

**Comment by jorymorrison** [comment]
Can you please create a branch for this fix?

**Comment by jorymorrison** [comment]
@Matthew-Zorumski Is this fixed? Or was the issue invalid? Please update here.

**Comment by Matthew-Zorumski** [comment]
This was invalidated when it was discovered that the username is now universally APIKEY and the password is the apikey you retrieve from IBM.

**Comment by jorymorrison** [comment]
Can you please update the documentation for tone analyzer?

**Comment by Matthew-Zorumski** [comment]
documentation updated in #11
